### ISSUE TITLE
Unattended installer docs should link to Visual C++ runtime

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/docs#120]
Enclave requires visual C++ runtime, but as far as I can't tell our [Unattended Installer](https://docs.enclave.io/setup/windows/#unattended-installation) docs don't link to or reference it. We should fix that.

**Comment by enclave-alistair** [comment]
The executable download already includes, the MSI one does not. There is already a "Note" admonition about this on the MSI tabs:


![Image](https://github.com/enclave-networks/docs/assets/67738909/62bba5db-a3ca-494f-bfbe-16eb06a20959)


Perhaps we just need to change this to warning.

**Comment by enclave-marc-barry** [comment]
Ohhhhhhhhh, it's in the `MSI` tab. Does the x64 executable not also require vc++ redist?

**Comment by enclave-alistair** [comment]
No, because the executable version includes vc++ redist in the bundle.

**Comment by enclave-marc-barry** [comment]
Fab, sounds like no action required then for this issue. Shall we close?
