### ISSUE TITLE
How should a customer secure access to a Linux system running Enclave? 

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/docs#33]
- How does a customer secure SSH when running Enclave?
- Is our advice bind SSH to an interface?
- How do updates to Enclave happen?
- What other kinds of things might a customer need to consider to provide secure access to SSH via Enclave?

We need an official line on this subject, an authority to which customers can refer to.

**Comment by enclave-tom** [comment]
Just some early investigation and thoughts right now if you add the enclave subnet to UFW with the commands below you can grant access to any enclave network. @enclave-alistair has discussed making this rule something we add to the firewall on the fabric start this way we can also narrow it down to the specific adapter. This should in theory remove any risk of damaging their existing setup. We will of course need to remove it when enclave is stopped.
```bash
sudo ufw allow 100.64.0.0/10
sudo ufw enable
```

**Comment by enclave-alistair** [comment]
Does ufw not remove the adapter rule from it's list when the adapter is removed, like the ip routing table?

**Comment by enclave-tom** [comment]
it hopefully does but it'll be a simple remove either way

**Comment by enclave-tom** [comment]
Relates to https://github.com/enclave-networks/fabric/issues/547

**Comment by enclave-tom** [comment]
> Thanks Tom, where do we go next with this issue?

I think we'll do a docs post intitially but aim to integrate this into the fabric so it's done automatically at runtime

**Comment by enclave-tom** [comment]
# Notes

# UFW
UFW is a simple firewall configuration tool which has been developed to ease the configuration of `iptables` it's incredibly user friendly and is the default firewall on Ubuntu, so here we'll be learning how to configure it for use with `enclave`.


When using enclave the best way to enable secure access to your System, is to grant a rule for the entire enclave subnet this is `100.64.0.0/10`. 

To do this we'll start with a disabled UFW firewall for the sake of this tutorial however we'll also provide some tips on how best to set UFW up at the end of this blog if you have existing rules.

First let's add our subnet rule, this will add a rule to allow any traffic from this subnet through to your system.
```bash
sudo ufw allow 100.64.0.0/10
```

We'll also allow SSH connections here to ensure that you don't drop connectivity when you enable the firewall
```bash
sudo ufw allow ssh
```

Next let's enable the firewall
```bash
sudo ufw enable
```
> This step is only needed if you haven't already got UFW enabled.


The firewall is now running and you're connected over SSH what we'll need to do is connect to the system using the enclave IP Address. For example it may look like this `100.65.xxx.xxx`.

Once you're connected over enclave you can remove the SSH rule.
```bash
sudo ufw delete allow ssh
```

And we're done you now have full access to your system over enclave. 


# Migrating access
If you've already got UFW setup and would like to lock down access to enclave specifically follow the tutorial above while excluding the `enable` step.

Once you've done that connect back to your System over `enclave`. From here start removing any rules you've added by using the following commands
```bash
sudo ufw status numbered
```

And then just do 
```bash
sudo ufw delete [INDEX]
```

> WARNING: The indexes may change as you're deleting so we recommend re running `sudo ufw status numbered` after every delete action.

**Comment by enclave-marc-barry** [comment]
What's the next action on this issue gents?
