### ISSUE TITLE
How to use Enclave Gateway in WSL on Windows

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/docs#62]
@bcronje you mentioned in #engineering channel "Gateway on WSL should work fine. Just tested with default route sitting on WSL and enclave client on a VM and it functions as you'd expect it should."

Would be great to get a how-to guide drafted into docs. Think you’d be able to help? We’ve got a customer asking how to run an Enclave Gateway on Windows, I'd love to be able to show them a how-to guide.

If you're able to help, do you think you could give me an estimate of how much time you'd need?

**Comment by enclave-marc-barry** [comment]
On reflection, I think we can palm that off to Google and caveat the doc with an admonition along the lines of "you need WSL for Windows". It might be this is a sub-section or update to the existing Gateway docs page https://docs.enclave.io/management/gateways/#limitations

Not sure it's need to be too concerned with anything beyond the Enclave steps, if it's just a case of run Enclave inside of a WSL image on Windows and set the host network up correctly all to the good. Just would be nice for our docs to take a view on this for interested parties.

**Comment by bcronje** [comment]
I *think* it's literally just installing Enclave in WSL and configuring your policies. But, I am currently running a somewhat non-standard WSL installation at the moment, for instance my default login is root. So I'll just confirm what is needed from a fresh install.

**Comment by bcronje** [comment]
WSL2 basically creates a virtual switch on the Windows host that sits in that `172.30.32.0/20` subnet, it adds a new WSL adapter in your Windows host that also sits in that subnet and acts as a default gateway to WSL. It then basically just does NAT from your WSL Ubuntu instance out the Windows. So by default connectivity from WSL out just works out the box.

Incoming connections into WSL does not work by default without setting up some static NAT entries and opening FW ports on the Windows host. I've read this is possible, but I haven't played around with static NAT and WSL before.
So just using everything on defaults it seems to end up establishing Enclave peer connections via relay and not direct. I guess this is not ideal?

**Comment by bcronje** [comment]
@enclave-marc-barry just a quick update. I've tried setting WSL up to connect directly with peers and not end up with Enclave relay connections by setting up static port forwarding on the WSL Windows host and opening up the Windows firewall for this port. Some observations so far:

The Windows `netsh interface portproxy` command used to configure the port forwarding only supports TCP. So at best we will only be able to connect via TCP. Still better than a relay connection though.

I then tried to configured Enclave to use the port configured for port forwarding on the Windows host by using the Enclave `LocalPort` profile setting. But this setting does not seem to change my local port at all as Enclave still ends up using a random port. @enclave-alistair  is `LocalPort` suppose to be used for what I want to achieve, i.e. force Enclave TCP/UDP to use that port?

Unfortunately I've run out of time to work on this further tonight. I'm unfortunately also out of town for most of the coming week, so I'll only be able to dig into this further next weekend.

Just for interest, the following commands were used on the Windows host to enable port forwarding and open the firewall:

```
netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=3333 connectaddress=172.17.242.61 connectport=3333

netsh advfirewall firewall add rule name="Enclave Open Port 3333 for WSL2" dir=in action=allow protocol=TCP localport=3333
```

And then in WSL `Universe.profile`
```
"LocalPort": 3333,
```

**Comment by enclave-alistair** [comment]
@bcronje, Enclave _should_ allow you to set that local port value.  If you're on the latest GA, could you run `enclave list-config` to display the port? Then `enclave set-config localport 3333` to change it.

@enclave-marc-barry; if we're ok with that caveat, then yes, we should update the gateway docs with a section on running inside WSL (probably with the note that it's suboptimal, and should only be done if spinning up a Linux box just isn't viable.

**Comment by enclave-alistair** [comment]
We should include a note that running Enclave Gateway in a docker container on Windows using Docker Desktop will have similar challenges, because Docker Desktop runs on top of WSL.

**Comment by bcronje** [comment]
@enclave-alistair `enclave list-config` shows the configured port, but it does not appear to be used anywhere. None of the tcp/udp ports used by enclave seems to be using the configured port:

```
bcronje@DESKTOP-FLBILB3:~$ sudo cat /etc/enclave/profiles/Universe.profile | grep LocalPort
  "LocalPort": 2222,

bcronje@DESKTOP-FLBILB3:~$ sudo enclave list-config
name      current       default                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                    
localport 2222          0             Defines the local binding port used for enclave connectivity. The default value of 0 means enclave will choose a random high port for connectivity each time it re-establishes a route to our platform.

bcronje@DESKTOP-FLBILB3:~$ sudo netstat -tulpn | grep enclave
tcp        0      0 100.72.99.87:53         0.0.0.0:*               LISTEN      467/enclave         
tcp        0      0 127.0.0.1:35489         0.0.0.0:*               LISTEN      467/enclave         
tcp        0      0 172.17.242.61:39549     0.0.0.0:*               LISTEN      467/enclave         
tcp        0      0 127.0.0.1:42797         0.0.0.0:*               LISTEN      14/enclave          
udp        0      0 100.72.99.87:53         0.0.0.0:*                           467/enclave         
udp        0      0 172.17.242.61:39549     0.0.0.0:*                           467/enclave         

bcronje@DESKTOP-FLBILB3:~$ sudo netstat -tupn | grep enclave
tcp        0      0 172.17.242.61:39549     161.35.171.235:443      ESTABLISHED 467/enclave         
tcp        0      0 172.17.242.61:39077     167.99.199.8:443        ESTABLISHED 467/enclave
```

**Comment by enclave-alistair** [comment]
@bcronje, what does `enclave status` report the local endpoints are?

e.g.
![image](https://user-images.githubusercontent.com/67738909/231443665-3cb221f5-80f5-4b5c-884a-384c6d512442.png)

**Comment by enclave-alistair** [comment]
Oh, I've just been through the code and realised that the local endpoint reset used for reacting to DS changes seems to ignore the configured port.

I'll raise a separate issue to track that.

**Comment by enclave-marc-barry** [comment]
Appreciate the note [added to docs](https://docs.enclave.io/management/gateways/):

> If you cannot deploy a Linux VM or Linux-compatible device, Enclave can run as a gateway inside [WSL2 on a Windows Server](https://learn.microsoft.com/en-us/windows/wsl/install-on-server). Note that WSL2 places a number of requirements on the environment in which the Windows instance is running, which may make this option more complicated than just deploying a Linux VM.

But could you take a moment to expand that paragraph to describe in more concrete terms what "more complicated than just deploying a Linux VM" means?

At the moment that reads para reads as, "you can - but don't" which I'm not sure is that useful.

**Comment by enclave-alistair** [comment]
Done; docs updated.
