### ISSUE TITLE
The "Organisations" page is extremely bare

### ISSUE THREAD

**Issue by enclave-charlie** [enclave-networks/docs#68]
![image](https://user-images.githubusercontent.com/112474401/235628570-36d57a5d-2ab0-487d-9b1d-dd889f3d3994.png)

(Found by searching for "organisations", or at https://docs.enclave.io/management/organisations/)

**Comment by enclave-charlie** [comment]
Think it's enough that the file is empty. Seems to only be searchable by the content, rather than the file name.

**Comment by enclave-charlie** [comment]
Does feel odd to have placeholder files in our docs, though. Wouldn't we be better off just raising an issue?

**Comment by enclave-tom** [comment]
closed by #89
