### ISSUE TITLE
Add visibility of 32-bit unattended installer to setup page

### ISSUE THREAD

**Issue by enclave-tom** [enclave-networks/docs#73]
This should also include any relevant information. such as why we only unatteded for win 7 32 bit and also related information from this issue https://github.com/enclave-networks/fabric/issues/695

**Comment by enclave-marc-barry** [comment]
fixed the windows install docs to reference 32-bit and added tabs to make it clearer which file for which arc a customer or partner needs. This leaves a gaping hole in the portal, ofc

we'll need an issue in the portal to address the duplication we have there. I wonder if there's a better option than to duplicate all of this information again in the portal..?

**Comment by enclave-alistair** [comment]
There's a link to docs in the portal "Want to deploy unattended?". Closing this as the docs are now there for unattended.
